

export const rows = [
  {
    id: 1,
    name: "Jon Snow",
    email: "jonsnow@gmail.com",
    age: 35,
    phone: "(444)545-8794",
    access: "Admin",
  },
  {
    id: 2,
    name: "Cersei Lannister",
    email: "CerseiLannister@gmail.com",
    age: 42,
    phone: "(354)412-1223",
    access: "Admin",
  },
  {
    id: 3,
    name: "Anya Lannister",
    email: "AnyaLannister@gmail.com",
    age: 45,
    phone: "(111)544-8474",
    access: "Admin",
  },
  {
    id: 4,
    name: "Jaime Stark",
    email: "JaimeStark@gmail.com",
    age: 16,
    phone: "(777)485-8792",
    access: "Manager",
  },
  {
    id: 5,
    name: "Jacky Targaryen",
    email: "JackyTargaryen",
    age: 25,
    phone: "(147)748-1004",
    access: "Manager",
  },
  {
    id: 6,
    name: "Ever Melisandre",
    email: "EverMelisandre@gmail.com",
    age: 150,
    phone: "(222)444-4587",
    access: "User",
  },
  {
    id: 7,
    name: "ferrara Clifford",
    email: "ferraraClifford@gmail.com",
    age: 44,
    phone: "(555)852-1254",
    access: "User",
  },
  {
    id: 8,
    name: "Rossini Frances",
    email: "RossiniFrances@gmai.com",
    age: 36,
    phone: "(125)235-1000",
    access: "User",
  },
  {
    id: 9,
    name: "Harvey Roxie",
    email: "HarveyRoxie@gmai.com",
    age: 65,
    phone: "(478)423-4556",
    access: "User",
  },
];
